CREATE TABLE `generic_master_fact` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `co_account_id` bigint(20) NOT NULL,
  `co_project_id` bigint(20) NOT NULL,
  `co_video_id` bigint(20) NOT NULL,
  `pub_account_id` bigint(20) NOT NULL,
  `source_id` smallint NOT NULL,
  `country_id` int(3) NOT NULL,
  `content_type` int(2) NOT NULL DEFAULT 0,
  `device_id` int(2) NOT NULL DEFAULT 1,
  `day` date NOT NULL,
  `loads` bigint(20),
  `plays` bigint(20),
  `ad_clicks` int(11),
  `ad_impressions` int(11),
  `ad_revenue` float(11,4),
  `ecpm` float(14,7),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_key` (`co_account_id`, `co_project_id`,`co_video_id`,`source_id`,`pub_account_id`,`country_id`, `content_type`, `device_id`,`day`),
  KEY `co_account_id` (`co_account_id`),
  KEY `co_project_id` (`co_project_id`),
  KEY `co_video_id` (`co_video_id`),
  KEY `source_id` (`source_id`),
  KEY `pub_account_id` (`pub_account_id`),
  KEY `country_id` (`country_id`),
  KEY `device_id` (`device_id`),
  KEY `day` (`day`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `source_dimension` (
  `id` smallint NOT NULL,
  `source` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_key` (`source`),
  KEY `source` (`source`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `generic_account_daily_fact` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `co_account_id` bigint(20) NOT NULL,
  `pub_account_id` bigint(20) NOT NULL,
  `source_id` smallint NOT NULL,
  `content_type` int(2) NOT NULL DEFAULT 0,
  `day` date NOT NULL,
  `loads` bigint(20),
  `plays` bigint(20),
  `ad_clicks` int(11),
  `ad_impressions` int(11),
  `ad_revenue` float(11,4),
  `ecpm` float(14,7),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_key` (`co_account_id`,`pub_account_id`, `content_type`, `source_id`,`day`),
  KEY `co_account_id` (`co_account_id`),
  KEY `pub_account_id` (`pub_account_id`),
  KEY `source_id` (`source_id`),
  KEY `day` (`day`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE `generic_project_daily_fact` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `co_account_id` bigint(20) NOT NULL,
  `co_project_id` bigint(20) NOT NULL,
  `pub_account_id` bigint(20) NOT NULL,
  `content_type` int(2) NOT NULL DEFAULT 0,
  `source_id` smallint NOT NULL,
  `reporting_source` varchar(255) NOT NULL,
  `day` date NOT NULL,
  `loads` bigint(20),
  `plays` bigint(20),
  `ad_clicks` int(11),
  `ad_impressions` int(11),
  `ad_revenue` float(11,4),
  `ecpm` float(14,7),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_key` (`co_account_id`, `co_project_id`,`pub_account_id`, `content_type`, `source_id`,`day`),
  KEY `co_account_id` (`co_account_id`),
  KEY `co_project_id` (`co_project_id`),
  KEY `pub_account_id` (`pub_account_id`),
  KEY `source_id` (`source_id`),
  KEY `day` (`day`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE `generic_video_daily_fact` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `co_account_id` bigint(20) NOT NULL,
  `co_project_id` bigint(20) NOT NULL,
  `co_video_id` bigint(20) NOT NULL,
  `pub_account_id` bigint(20) NOT NULL,
  `content_type` int(2) NOT NULL DEFAULT 0,
  `source_id` smallint NOT NULL,
  `day` date NOT NULL,
  `loads` bigint(20),
  `plays` bigint(20),
  `ad_clicks` int(11),
  `ad_impressions` int(11),
  `ad_revenue` float(11,4),
  `ecpm` float(14,7),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_key` (`co_account_id`, `co_project_id`,`co_video_id`, `content_type`, `pub_account_id`,`source_id`,`day`),
  KEY `co_account_id` (`co_account_id`),
  KEY `co_project_id` (`co_project_id`),
  KEY `co_video_id` (`co_video_id`),
  KEY `pub_account_id` (`pub_account_id`),
  KEY `source_id` (`source_id`),
  KEY `day` (`day`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE `generic_country_daily_fact` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `co_account_id` bigint(20) NOT NULL,
  `co_project_id` bigint(20) NOT NULL,
  `co_video_id` bigint(20) NOT NULL,
  `pub_account_id` bigint(20) NOT NULL,
  `content_type` int(2) NOT NULL DEFAULT 0,
  `source_id` smallint NOT NULL,
  `country_id` int(3) NOT NULL,
  `day` date NOT NULL,
  `loads` bigint(20),
  `plays` bigint(20),
  `ad_clicks` int(11),
  `ad_impressions` int(11),
  `ad_revenue` float(11,4),
  `ecpm` float(14,7),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_key` (`co_account_id`, `co_project_id`,`co_video_id`,`pub_account_id`,`source_id`, `content_type`, `country_id`,`day`),
  KEY `co_account_id` (`co_account_id`),
  KEY `co_project_id` (`co_project_id`),
  KEY `co_video_id` (`co_video_id`),
  KEY `pub_account_id` (`pub_account_id`),
  KEY `source_id` (`source_id`),
  KEY `country_id` (`country_id`),
  KEY `day` (`day`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE `generic_device_daily_fact` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `co_account_id` bigint(20) NOT NULL,
  `co_project_id` bigint(20) NOT NULL,
  `co_video_id` bigint(20) NOT NULL,
  `pub_account_id` bigint(20) NOT NULL,
  `content_type` int(2) NOT NULL DEFAULT 0,
  `source_id` smallint NOT NULL,
  `device_id` int(2) NOT NULL DEFAULT 1,
  `day` date NOT NULL,
  `loads` bigint(20),
  `plays` bigint(20),
  `ad_clicks` int(11),
  `ad_impressions` int(11),
  `ad_revenue` float(11,4),
  `ecpm` float(14,7),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_key` (`co_account_id`, `co_project_id`,`co_video_id`,`pub_account_id`, `content_type`, `source_id`,`device_id`,`day`),
  KEY `co_account_id` (`co_account_id`),
  KEY `co_project_id` (`co_project_id`),
  KEY `co_video_id` (`co_video_id`),
  KEY `pub_account_id` (`pub_account_id`),
  KEY `source_id` (`source_id`),
  KEY `device_id` (`device_id`),
  KEY `day` (`day`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
